-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Movie"
(
    "ID" bigserial NOT NULL,
    "Title" character varying(160) COLLATE pg_catalog."default" NOT NULL,
    "Description" text COLLATE pg_catalog."default" NOT NULL,
    "Year" integer NOT NULL,
    "Runtime" integer NOT NULL,
    CONSTRAINT "Movies_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."Room"
(
    "ID" smallserial NOT NULL,
    "Number" character(20) COLLATE pg_catalog."default" NOT NULL,
    "Seats" smallint NOT NULL,
    CONSTRAINT "Rooms_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."Show"
(
    "ID" bigserial NOT NULL,
    "MovieID" bigserial NOT NULL,
    "RoomID" smallserial NOT NULL,
    "StartTime" timestamp without time zone NOT NULL,
    CONSTRAINT "Shows_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."Ticket"
(
    "ID" bigserial NOT NULL,
    "UserID" bigserial NOT NULL,
    "ShowID" bigserial NOT NULL,
    "SeatNumber" smallint NOT NULL,
    CONSTRAINT "Tickets_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."User"
(
    "ID" bigserial NOT NULL,
    "UUID" uuid NOT NULL,
    "Login" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Password" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Email" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "CurrentSessionUUID" uuid,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "User_pkey" PRIMARY KEY ("ID")
);

ALTER TABLE IF EXISTS public."Show"
    ADD CONSTRAINT "Show_RoomID_fkey" FOREIGN KEY ("RoomID")
    REFERENCES public."Room" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Show"
    ADD FOREIGN KEY ("MovieID")
    REFERENCES public."Movie" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Ticket"
    ADD CONSTRAINT "Ticket_ShowID_fkey" FOREIGN KEY ("ShowID")
    REFERENCES public."Show" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Ticket"
    ADD FOREIGN KEY ("UserID")
    REFERENCES public."User" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;